// Generated by kea-typegen on Thu, 20 Jul 2023 10:55:48 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ExportedData } from './types'

export interface exporterViewLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'exporter', 'exporterLogic']
    pathString: 'scenes.exporter.exporterLogic'
    props: ExportedData
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        exportedData: (state: any, props?: any) => ExportedData
    }
    sharedListeners: {}
    values: {
        exportedData: ExportedData
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        exportedData: (arg: any) => ExportedData
    }
}
