// Generated by kea-typegen on Thu, 20 Jul 2023 11:14:25 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { SiteLogicProps } from './siteLogic'
import type { Breadcrumb } from '../../types'

export interface siteLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'sites', 'siteLogic']
    pathString: 'scenes.sites.siteLogic'
    props: SiteLogicProps
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
    }
    sharedListeners: {}
    values: {
        breadcrumbs: Breadcrumb[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        breadcrumbs: (url: string) => Breadcrumb[]
    }
}
