// Generated by kea-typegen on Tue, 08 Aug 2023 10:01:11 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { FeatureFlagLogicProps } from './featureFlagLogic'
import type { AnyPropertyFilter, AvailableFeature, Breadcrumb, DashboardBasicType, DashboardType, FeatureFlagType, FilterType, GroupType, InsightModel, MultivariateFlagOptions, MultivariateFlagVariant } from '../../types'
import type { TaxonomicFilterGroupType } from '../../lib/components/TaxonomicFilter/types'
import type { Noun } from '../../models/groupsModel'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from '../../../../node_modules/kea-forms'

export interface featureFlagLogicType extends Logic {
    actionCreators: {
        submitNewDashboardSuccessWithResult: (result: DashboardType) => {
            type: 'submit new dashboard success with result (scenes.feature-flags.featureFlagLogic)'
            payload: {
                result: DashboardType
            }
        }
        setFeatureFlag: (featureFlag: FeatureFlagType) => {
            type: 'set feature flag (scenes.feature-flags.featureFlagLogic)'
            payload: {
                featureFlag: FeatureFlagType
            }
        }
        setFeatureFlagMissing: () => {
            type: 'set feature flag missing (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: true
            }
        }
        addConditionSet: () => {
            type: 'add condition set (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: true
            }
        }
        addRollbackCondition: () => {
            type: 'add rollback condition (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: true
            }
        }
        setAggregationGroupTypeIndex: (value: number | null) => {
            type: 'set aggregation group type index (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: number | null
            }
        }
        removeConditionSet: (index: number) => {
            type: 'remove condition set (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
            }
        }
        removeRollbackCondition: (index: number) => {
            type: 'remove rollback condition (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
            }
        }
        duplicateConditionSet: (index: number) => {
            type: 'duplicate condition set (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
            }
        }
        updateConditionSet: (
            index: number,
            newRolloutPercentage?: number | null,
            newProperties?: AnyPropertyFilter[],
            newVariant?: string | null
        ) => {
            type: 'update condition set (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
                newRolloutPercentage: number | null | undefined
                newProperties: AnyPropertyFilter[] | undefined
                newVariant: string | null | undefined
            }
        }
        deleteFeatureFlag: (featureFlag: Partial<FeatureFlagType>) => {
            type: 'delete feature flag (scenes.feature-flags.featureFlagLogic)'
            payload: {
                featureFlag: Partial<FeatureFlagType>
            }
        }
        setMultivariateEnabled: (enabled: boolean) => {
            type: 'set multivariate enabled (scenes.feature-flags.featureFlagLogic)'
            payload: {
                enabled: boolean
            }
        }
        setMultivariateOptions: (multivariateOptions: MultivariateFlagOptions | null) => {
            type: 'set multivariate options (scenes.feature-flags.featureFlagLogic)'
            payload: {
                multivariateOptions: MultivariateFlagOptions | null
            }
        }
        addVariant: () => {
            type: 'add variant (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: true
            }
        }
        duplicateVariant: (index: number) => {
            type: 'duplicate variant (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
            }
        }
        removeVariant: (index: number) => {
            type: 'remove variant (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
            }
        }
        editFeatureFlag: (editing: boolean) => {
            type: 'edit feature flag (scenes.feature-flags.featureFlagLogic)'
            payload: {
                editing: boolean
            }
        }
        distributeVariantsEqually: () => {
            type: 'distribute variants equally (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: true
            }
        }
        loadInsightAtIndex: (
            index: number,
            filters: Partial<FilterType>
        ) => {
            type: 'load insight at index (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
                filters: Partial<FilterType>
            }
        }
        setInsightResultAtIndex: (
            index: number,
            average: number
        ) => {
            type: 'set insight result at index (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
                average: number
            }
        }
        loadAllInsightsForFlag: () => {
            type: 'load all insights for flag (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: true
            }
        }
        setAffectedUsers: (
            index: number,
            count?: number
        ) => {
            type: 'set affected users (scenes.feature-flags.featureFlagLogic)'
            payload: {
                index: number
                count: number | undefined
            }
        }
        setTotalUsers: (count: number) => {
            type: 'set total users (scenes.feature-flags.featureFlagLogic)'
            payload: {
                count: number
            }
        }
        triggerFeatureFlagUpdate: (payload: Partial<FeatureFlagType>) => {
            type: 'trigger feature flag update (scenes.feature-flags.featureFlagLogic)'
            payload: {
                payload: Partial<FeatureFlagType>
            }
        }
        generateUsageDashboard: () => {
            type: 'generate usage dashboard (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: true
            }
        }
        setFeatureFlagValue: (
            key: FieldName,
            value: any
        ) => {
            type: 'set feature flag value (scenes.feature-flags.featureFlagLogic)'
            payload: {
                name: FieldName
                value: any
            }
        }
        setFeatureFlagValues: (values: DeepPartial<FeatureFlagType>) => {
            type: 'set feature flag values (scenes.feature-flags.featureFlagLogic)'
            payload: {
                values: DeepPartial<FeatureFlagType>
            }
        }
        setFeatureFlagManualErrors: (errors: Record<string, any>) => {
            type: 'set feature flag manual errors (scenes.feature-flags.featureFlagLogic)'
            payload: {
                errors: Record<string, any>
            }
        }
        touchFeatureFlagField: (key: string) => {
            type: 'touch feature flag field (scenes.feature-flags.featureFlagLogic)'
            payload: {
                key: string
            }
        }
        resetFeatureFlag: (values?: FeatureFlagType) => {
            type: 'reset feature flag (scenes.feature-flags.featureFlagLogic)'
            payload: {
                values?: FeatureFlagType
            }
        }
        submitFeatureFlag: () => {
            type: 'submit feature flag (scenes.feature-flags.featureFlagLogic)'
            payload: {
                value: boolean
            }
        }
        submitFeatureFlagRequest: (featureFlag: FeatureFlagType) => {
            type: 'submit feature flag request (scenes.feature-flags.featureFlagLogic)'
            payload: {
                featureFlag: FeatureFlagType
            }
        }
        submitFeatureFlagSuccess: (featureFlag: FeatureFlagType) => {
            type: 'submit feature flag success (scenes.feature-flags.featureFlagLogic)'
            payload: {
                featureFlag: FeatureFlagType
            }
        }
        submitFeatureFlagFailure: (
            error: Error,
            errors: Record<string, any>
        ) => {
            type: 'submit feature flag failure (scenes.feature-flags.featureFlagLogic)'
            payload: {
                error: Error
                errors: Record<string, any>
            }
        }
        loadFeatureFlag: () => {
            type: 'load feature flag (scenes.feature-flags.featureFlagLogic)'
            payload: any
        }
        loadFeatureFlagSuccess: (
            featureFlag: FeatureFlagType,
            payload?: any
        ) => {
            type: 'load feature flag success (scenes.feature-flags.featureFlagLogic)'
            payload: {
                featureFlag: FeatureFlagType
                payload?: any
            }
        }
        loadFeatureFlagFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load feature flag failure (scenes.feature-flags.featureFlagLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        saveFeatureFlag: (updatedFlag: Partial<FeatureFlagType>) => {
            type: 'save feature flag (scenes.feature-flags.featureFlagLogic)'
            payload: Partial<FeatureFlagType>
        }
        saveFeatureFlagSuccess: (
            featureFlag: FeatureFlagType,
            payload?: Partial<FeatureFlagType>
        ) => {
            type: 'save feature flag success (scenes.feature-flags.featureFlagLogic)'
            payload: {
                featureFlag: FeatureFlagType
                payload?: Partial<FeatureFlagType>
            }
        }
        saveFeatureFlagFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'save feature flag failure (scenes.feature-flags.featureFlagLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        loadRecentInsights: () => {
            type: 'load recent insights (scenes.feature-flags.featureFlagLogic)'
            payload: any
        }
        loadRecentInsightsSuccess: (
            recentInsights: InsightModel[],
            payload?: any
        ) => {
            type: 'load recent insights success (scenes.feature-flags.featureFlagLogic)'
            payload: {
                recentInsights: InsightModel[]
                payload?: any
            }
        }
        loadRecentInsightsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load recent insights failure (scenes.feature-flags.featureFlagLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        loadSentryStats: () => {
            type: 'load sentry stats (scenes.feature-flags.featureFlagLogic)'
            payload: any
        }
        loadSentryStatsSuccess: (
            sentryStats: {
                total_count?: number
                sentry_integration_enabled?: number
            },
            payload?: any
        ) => {
            type: 'load sentry stats success (scenes.feature-flags.featureFlagLogic)'
            payload: {
                sentryStats: {
                    total_count?: number
                    sentry_integration_enabled?: number
                }
                payload?: any
            }
        }
        loadSentryStatsFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load sentry stats failure (scenes.feature-flags.featureFlagLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'submit new dashboard success with result (scenes.feature-flags.featureFlagLogic)': 'submitNewDashboardSuccessWithResult'
        'set feature flag (scenes.feature-flags.featureFlagLogic)': 'setFeatureFlag'
        'set feature flag missing (scenes.feature-flags.featureFlagLogic)': 'setFeatureFlagMissing'
        'add condition set (scenes.feature-flags.featureFlagLogic)': 'addConditionSet'
        'add rollback condition (scenes.feature-flags.featureFlagLogic)': 'addRollbackCondition'
        'set aggregation group type index (scenes.feature-flags.featureFlagLogic)': 'setAggregationGroupTypeIndex'
        'remove condition set (scenes.feature-flags.featureFlagLogic)': 'removeConditionSet'
        'remove rollback condition (scenes.feature-flags.featureFlagLogic)': 'removeRollbackCondition'
        'duplicate condition set (scenes.feature-flags.featureFlagLogic)': 'duplicateConditionSet'
        'update condition set (scenes.feature-flags.featureFlagLogic)': 'updateConditionSet'
        'delete feature flag (scenes.feature-flags.featureFlagLogic)': 'deleteFeatureFlag'
        'set multivariate enabled (scenes.feature-flags.featureFlagLogic)': 'setMultivariateEnabled'
        'set multivariate options (scenes.feature-flags.featureFlagLogic)': 'setMultivariateOptions'
        'add variant (scenes.feature-flags.featureFlagLogic)': 'addVariant'
        'duplicate variant (scenes.feature-flags.featureFlagLogic)': 'duplicateVariant'
        'remove variant (scenes.feature-flags.featureFlagLogic)': 'removeVariant'
        'edit feature flag (scenes.feature-flags.featureFlagLogic)': 'editFeatureFlag'
        'distribute variants equally (scenes.feature-flags.featureFlagLogic)': 'distributeVariantsEqually'
        'load insight at index (scenes.feature-flags.featureFlagLogic)': 'loadInsightAtIndex'
        'set insight result at index (scenes.feature-flags.featureFlagLogic)': 'setInsightResultAtIndex'
        'load all insights for flag (scenes.feature-flags.featureFlagLogic)': 'loadAllInsightsForFlag'
        'set affected users (scenes.feature-flags.featureFlagLogic)': 'setAffectedUsers'
        'set total users (scenes.feature-flags.featureFlagLogic)': 'setTotalUsers'
        'trigger feature flag update (scenes.feature-flags.featureFlagLogic)': 'triggerFeatureFlagUpdate'
        'generate usage dashboard (scenes.feature-flags.featureFlagLogic)': 'generateUsageDashboard'
        'set feature flag value (scenes.feature-flags.featureFlagLogic)': 'setFeatureFlagValue'
        'set feature flag values (scenes.feature-flags.featureFlagLogic)': 'setFeatureFlagValues'
        'set feature flag manual errors (scenes.feature-flags.featureFlagLogic)': 'setFeatureFlagManualErrors'
        'touch feature flag field (scenes.feature-flags.featureFlagLogic)': 'touchFeatureFlagField'
        'reset feature flag (scenes.feature-flags.featureFlagLogic)': 'resetFeatureFlag'
        'submit feature flag (scenes.feature-flags.featureFlagLogic)': 'submitFeatureFlag'
        'submit feature flag request (scenes.feature-flags.featureFlagLogic)': 'submitFeatureFlagRequest'
        'submit feature flag success (scenes.feature-flags.featureFlagLogic)': 'submitFeatureFlagSuccess'
        'submit feature flag failure (scenes.feature-flags.featureFlagLogic)': 'submitFeatureFlagFailure'
        'load feature flag (scenes.feature-flags.featureFlagLogic)': 'loadFeatureFlag'
        'load feature flag success (scenes.feature-flags.featureFlagLogic)': 'loadFeatureFlagSuccess'
        'load feature flag failure (scenes.feature-flags.featureFlagLogic)': 'loadFeatureFlagFailure'
        'save feature flag (scenes.feature-flags.featureFlagLogic)': 'saveFeatureFlag'
        'save feature flag success (scenes.feature-flags.featureFlagLogic)': 'saveFeatureFlagSuccess'
        'save feature flag failure (scenes.feature-flags.featureFlagLogic)': 'saveFeatureFlagFailure'
        'load recent insights (scenes.feature-flags.featureFlagLogic)': 'loadRecentInsights'
        'load recent insights success (scenes.feature-flags.featureFlagLogic)': 'loadRecentInsightsSuccess'
        'load recent insights failure (scenes.feature-flags.featureFlagLogic)': 'loadRecentInsightsFailure'
        'load sentry stats (scenes.feature-flags.featureFlagLogic)': 'loadSentryStats'
        'load sentry stats success (scenes.feature-flags.featureFlagLogic)': 'loadSentryStatsSuccess'
        'load sentry stats failure (scenes.feature-flags.featureFlagLogic)': 'loadSentryStatsFailure'
    }
    actionTypes: {
        submitNewDashboardSuccessWithResult: 'submit new dashboard success with result (scenes.feature-flags.featureFlagLogic)'
        setFeatureFlag: 'set feature flag (scenes.feature-flags.featureFlagLogic)'
        setFeatureFlagMissing: 'set feature flag missing (scenes.feature-flags.featureFlagLogic)'
        addConditionSet: 'add condition set (scenes.feature-flags.featureFlagLogic)'
        addRollbackCondition: 'add rollback condition (scenes.feature-flags.featureFlagLogic)'
        setAggregationGroupTypeIndex: 'set aggregation group type index (scenes.feature-flags.featureFlagLogic)'
        removeConditionSet: 'remove condition set (scenes.feature-flags.featureFlagLogic)'
        removeRollbackCondition: 'remove rollback condition (scenes.feature-flags.featureFlagLogic)'
        duplicateConditionSet: 'duplicate condition set (scenes.feature-flags.featureFlagLogic)'
        updateConditionSet: 'update condition set (scenes.feature-flags.featureFlagLogic)'
        deleteFeatureFlag: 'delete feature flag (scenes.feature-flags.featureFlagLogic)'
        setMultivariateEnabled: 'set multivariate enabled (scenes.feature-flags.featureFlagLogic)'
        setMultivariateOptions: 'set multivariate options (scenes.feature-flags.featureFlagLogic)'
        addVariant: 'add variant (scenes.feature-flags.featureFlagLogic)'
        duplicateVariant: 'duplicate variant (scenes.feature-flags.featureFlagLogic)'
        removeVariant: 'remove variant (scenes.feature-flags.featureFlagLogic)'
        editFeatureFlag: 'edit feature flag (scenes.feature-flags.featureFlagLogic)'
        distributeVariantsEqually: 'distribute variants equally (scenes.feature-flags.featureFlagLogic)'
        loadInsightAtIndex: 'load insight at index (scenes.feature-flags.featureFlagLogic)'
        setInsightResultAtIndex: 'set insight result at index (scenes.feature-flags.featureFlagLogic)'
        loadAllInsightsForFlag: 'load all insights for flag (scenes.feature-flags.featureFlagLogic)'
        setAffectedUsers: 'set affected users (scenes.feature-flags.featureFlagLogic)'
        setTotalUsers: 'set total users (scenes.feature-flags.featureFlagLogic)'
        triggerFeatureFlagUpdate: 'trigger feature flag update (scenes.feature-flags.featureFlagLogic)'
        generateUsageDashboard: 'generate usage dashboard (scenes.feature-flags.featureFlagLogic)'
        setFeatureFlagValue: 'set feature flag value (scenes.feature-flags.featureFlagLogic)'
        setFeatureFlagValues: 'set feature flag values (scenes.feature-flags.featureFlagLogic)'
        setFeatureFlagManualErrors: 'set feature flag manual errors (scenes.feature-flags.featureFlagLogic)'
        touchFeatureFlagField: 'touch feature flag field (scenes.feature-flags.featureFlagLogic)'
        resetFeatureFlag: 'reset feature flag (scenes.feature-flags.featureFlagLogic)'
        submitFeatureFlag: 'submit feature flag (scenes.feature-flags.featureFlagLogic)'
        submitFeatureFlagRequest: 'submit feature flag request (scenes.feature-flags.featureFlagLogic)'
        submitFeatureFlagSuccess: 'submit feature flag success (scenes.feature-flags.featureFlagLogic)'
        submitFeatureFlagFailure: 'submit feature flag failure (scenes.feature-flags.featureFlagLogic)'
        loadFeatureFlag: 'load feature flag (scenes.feature-flags.featureFlagLogic)'
        loadFeatureFlagSuccess: 'load feature flag success (scenes.feature-flags.featureFlagLogic)'
        loadFeatureFlagFailure: 'load feature flag failure (scenes.feature-flags.featureFlagLogic)'
        saveFeatureFlag: 'save feature flag (scenes.feature-flags.featureFlagLogic)'
        saveFeatureFlagSuccess: 'save feature flag success (scenes.feature-flags.featureFlagLogic)'
        saveFeatureFlagFailure: 'save feature flag failure (scenes.feature-flags.featureFlagLogic)'
        loadRecentInsights: 'load recent insights (scenes.feature-flags.featureFlagLogic)'
        loadRecentInsightsSuccess: 'load recent insights success (scenes.feature-flags.featureFlagLogic)'
        loadRecentInsightsFailure: 'load recent insights failure (scenes.feature-flags.featureFlagLogic)'
        loadSentryStats: 'load sentry stats (scenes.feature-flags.featureFlagLogic)'
        loadSentryStatsSuccess: 'load sentry stats success (scenes.feature-flags.featureFlagLogic)'
        loadSentryStatsFailure: 'load sentry stats failure (scenes.feature-flags.featureFlagLogic)'
    }
    actions: {
        submitNewDashboardSuccessWithResult: (result: DashboardType) => void
        setFeatureFlag: (featureFlag: FeatureFlagType) => void
        setFeatureFlagMissing: () => void
        addConditionSet: () => void
        addRollbackCondition: () => void
        setAggregationGroupTypeIndex: (value: number | null) => void
        removeConditionSet: (index: number) => void
        removeRollbackCondition: (index: number) => void
        duplicateConditionSet: (index: number) => void
        updateConditionSet: (
            index: number,
            newRolloutPercentage?: number | null,
            newProperties?: AnyPropertyFilter[],
            newVariant?: string | null
        ) => void
        deleteFeatureFlag: (featureFlag: Partial<FeatureFlagType>) => void
        setMultivariateEnabled: (enabled: boolean) => void
        setMultivariateOptions: (multivariateOptions: MultivariateFlagOptions | null) => void
        addVariant: () => void
        duplicateVariant: (index: number) => void
        removeVariant: (index: number) => void
        editFeatureFlag: (editing: boolean) => void
        distributeVariantsEqually: () => void
        loadInsightAtIndex: (index: number, filters: Partial<FilterType>) => void
        setInsightResultAtIndex: (index: number, average: number) => void
        loadAllInsightsForFlag: () => void
        setAffectedUsers: (index: number, count?: number) => void
        setTotalUsers: (count: number) => void
        triggerFeatureFlagUpdate: (payload: Partial<FeatureFlagType>) => void
        generateUsageDashboard: () => void
        setFeatureFlagValue: (key: FieldName, value: any) => void
        setFeatureFlagValues: (values: DeepPartial<FeatureFlagType>) => void
        setFeatureFlagManualErrors: (errors: Record<string, any>) => void
        touchFeatureFlagField: (key: string) => void
        resetFeatureFlag: (values?: FeatureFlagType) => void
        submitFeatureFlag: () => void
        submitFeatureFlagRequest: (featureFlag: FeatureFlagType) => void
        submitFeatureFlagSuccess: (featureFlag: FeatureFlagType) => void
        submitFeatureFlagFailure: (error: Error, errors: Record<string, any>) => void
        loadFeatureFlag: () => void
        loadFeatureFlagSuccess: (featureFlag: FeatureFlagType, payload?: any) => void
        loadFeatureFlagFailure: (error: string, errorObject?: any) => void
        saveFeatureFlag: (updatedFlag: Partial<FeatureFlagType>) => void
        saveFeatureFlagSuccess: (featureFlag: FeatureFlagType, payload?: Partial<FeatureFlagType>) => void
        saveFeatureFlagFailure: (error: string, errorObject?: any) => void
        loadRecentInsights: () => void
        loadRecentInsightsSuccess: (recentInsights: InsightModel[], payload?: any) => void
        loadRecentInsightsFailure: (error: string, errorObject?: any) => void
        loadSentryStats: () => void
        loadSentryStatsSuccess: (
            sentryStats: {
                total_count?: number
                sentry_integration_enabled?: number
            },
            payload?: any
        ) => void
        loadSentryStatsFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        submitNewDashboardSuccessWithResult: (result: DashboardType) => Promise<any>
        setFeatureFlag: (featureFlag: FeatureFlagType) => Promise<any>
        setFeatureFlagMissing: () => Promise<any>
        addConditionSet: () => Promise<any>
        addRollbackCondition: () => Promise<any>
        setAggregationGroupTypeIndex: (value: number | null) => Promise<any>
        removeConditionSet: (index: number) => Promise<any>
        removeRollbackCondition: (index: number) => Promise<any>
        duplicateConditionSet: (index: number) => Promise<any>
        updateConditionSet: (
            index: number,
            newRolloutPercentage?: number | null,
            newProperties?: AnyPropertyFilter[],
            newVariant?: string | null
        ) => Promise<any>
        deleteFeatureFlag: (featureFlag: Partial<FeatureFlagType>) => Promise<any>
        setMultivariateEnabled: (enabled: boolean) => Promise<any>
        setMultivariateOptions: (multivariateOptions: MultivariateFlagOptions | null) => Promise<any>
        addVariant: () => Promise<any>
        duplicateVariant: (index: number) => Promise<any>
        removeVariant: (index: number) => Promise<any>
        editFeatureFlag: (editing: boolean) => Promise<any>
        distributeVariantsEqually: () => Promise<any>
        loadInsightAtIndex: (index: number, filters: Partial<FilterType>) => Promise<any>
        setInsightResultAtIndex: (index: number, average: number) => Promise<any>
        loadAllInsightsForFlag: () => Promise<any>
        setAffectedUsers: (index: number, count?: number) => Promise<any>
        setTotalUsers: (count: number) => Promise<any>
        triggerFeatureFlagUpdate: (payload: Partial<FeatureFlagType>) => Promise<any>
        generateUsageDashboard: () => Promise<any>
        setFeatureFlagValue: (key: FieldName, value: any) => Promise<any>
        setFeatureFlagValues: (values: DeepPartial<FeatureFlagType>) => Promise<any>
        setFeatureFlagManualErrors: (errors: Record<string, any>) => Promise<any>
        touchFeatureFlagField: (key: string) => Promise<any>
        resetFeatureFlag: (values?: FeatureFlagType) => Promise<any>
        submitFeatureFlag: () => Promise<any>
        submitFeatureFlagRequest: (featureFlag: FeatureFlagType) => Promise<any>
        submitFeatureFlagSuccess: (featureFlag: FeatureFlagType) => Promise<any>
        submitFeatureFlagFailure: (error: Error, errors: Record<string, any>) => Promise<any>
        loadFeatureFlag: () => Promise<any>
        loadFeatureFlagSuccess: (featureFlag: FeatureFlagType, payload?: any) => Promise<any>
        loadFeatureFlagFailure: (error: string, errorObject?: any) => Promise<any>
        saveFeatureFlag: (updatedFlag: Partial<FeatureFlagType>) => Promise<any>
        saveFeatureFlagSuccess: (featureFlag: FeatureFlagType, payload?: Partial<FeatureFlagType>) => Promise<any>
        saveFeatureFlagFailure: (error: string, errorObject?: any) => Promise<any>
        loadRecentInsights: () => Promise<any>
        loadRecentInsightsSuccess: (recentInsights: InsightModel[], payload?: any) => Promise<any>
        loadRecentInsightsFailure: (error: string, errorObject?: any) => Promise<any>
        loadSentryStats: () => Promise<any>
        loadSentryStatsSuccess: (
            sentryStats: {
                total_count?: number
                sentry_integration_enabled?: number
            },
            payload?: any
        ) => Promise<any>
        loadSentryStatsFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        featureFlag: FeatureFlagType
        isFeatureFlagSubmitting: boolean
        showFeatureFlagErrors: boolean
        featureFlagChanged: boolean
        featureFlagTouches: Record<string, boolean>
        featureFlagManualErrors: Record<string, any>
        featureFlagMissing: boolean
        isEditingFlag: boolean
        insightRollingAverages: {}
        affectedUsers: {}
        totalUsers: number | null
        featureFlagLoading: boolean
        recentInsights: InsightModel[]
        recentInsightsLoading: boolean
        sentryStats: {
            total_count?: number
            sentry_integration_enabled?: number
        }
        sentryStatsLoading: boolean
    }
    events: {}
    key: number | 'new' | 'link'
    listeners: {
        submitNewDashboardSuccessWithResult: ((
            action: {
                type: 'submit new dashboard success with result (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    result: DashboardType
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        generateUsageDashboard: ((
            action: {
                type: 'generate usage dashboard (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        saveFeatureFlagSuccess: ((
            action: {
                type: 'save feature flag success (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    featureFlag: FeatureFlagType
                    payload?: Partial<FeatureFlagType>
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        deleteFeatureFlag: ((
            action: {
                type: 'delete feature flag (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    featureFlag: Partial<FeatureFlagType>
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        setMultivariateEnabled: ((
            action: {
                type: 'set multivariate enabled (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    enabled: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadFeatureFlagSuccess: ((
            action: {
                type: 'load feature flag success (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    featureFlag: FeatureFlagType
                    payload?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadInsightAtIndex: ((
            action: {
                type: 'load insight at index (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    index: number
                    filters: Partial<FilterType>
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadAllInsightsForFlag: ((
            action: {
                type: 'load all insights for flag (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        addRollbackCondition: ((
            action: {
                type: 'add rollback condition (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        updateConditionSet: ((
            action: {
                type: 'update condition set (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    index: number
                    newRolloutPercentage: number | null | undefined
                    newProperties: AnyPropertyFilter[] | undefined
                    newVariant: string | null | undefined
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        addConditionSet: ((
            action: {
                type: 'add condition set (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        editFeatureFlag: ((
            action: {
                type: 'edit feature flag (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    editing: boolean
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        triggerFeatureFlagUpdate: ((
            action: {
                type: 'trigger feature flag update (scenes.feature-flags.featureFlagLogic)'
                payload: {
                    payload: Partial<FeatureFlagType>
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['scenes', 'feature-flags', 'featureFlagLogic']
    pathString: 'scenes.feature-flags.featureFlagLogic'
    props: FeatureFlagLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        featureFlag: FeatureFlagType
        isFeatureFlagSubmitting: boolean
        showFeatureFlagErrors: boolean
        featureFlagChanged: boolean
        featureFlagTouches: Record<string, boolean>
        featureFlagManualErrors: Record<string, any>
        featureFlagMissing: boolean
        isEditingFlag: boolean
        insightRollingAverages: {}
        affectedUsers: {}
        totalUsers: number | null
        featureFlagLoading: boolean
        recentInsights: InsightModel[]
        recentInsightsLoading: boolean
        sentryStats: {
            total_count?: number
            sentry_integration_enabled?: number
        }
        sentryStatsLoading: boolean
    }
    reducers: {
        featureFlag: (state: FeatureFlagType, action: any, fullState: any) => FeatureFlagType
        isFeatureFlagSubmitting: (state: boolean, action: any, fullState: any) => boolean
        showFeatureFlagErrors: (state: boolean, action: any, fullState: any) => boolean
        featureFlagChanged: (state: boolean, action: any, fullState: any) => boolean
        featureFlagTouches: (state: Record<string, boolean>, action: any, fullState: any) => Record<string, boolean>
        featureFlagManualErrors: (state: Record<string, any>, action: any, fullState: any) => Record<string, any>
        featureFlagMissing: (state: boolean, action: any, fullState: any) => boolean
        isEditingFlag: (state: boolean, action: any, fullState: any) => boolean
        insightRollingAverages: (state: {}, action: any, fullState: any) => {}
        affectedUsers: (state: {}, action: any, fullState: any) => {}
        totalUsers: (state: number | null, action: any, fullState: any) => number | null
        featureFlagLoading: (state: boolean, action: any, fullState: any) => boolean
        recentInsights: (state: InsightModel[], action: any, fullState: any) => InsightModel[]
        recentInsightsLoading: (state: boolean, action: any, fullState: any) => boolean
        sentryStats: (
            state: {
                total_count?: number
                sentry_integration_enabled?: number
            },
            action: any,
            fullState: any
        ) => {
            total_count?: number
            sentry_integration_enabled?: number
        }
        sentryStatsLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        featureFlag: FeatureFlagType
        isFeatureFlagSubmitting: boolean
        showFeatureFlagErrors: boolean
        featureFlagChanged: boolean
        featureFlagTouches: Record<string, boolean>
        featureFlagManualErrors: Record<string, any>
        featureFlagMissing: boolean
        isEditingFlag: boolean
        insightRollingAverages: {}
        affectedUsers: {}
        totalUsers: number | null
        featureFlagLoading: boolean
        recentInsights: InsightModel[]
        recentInsightsLoading: boolean
        sentryStats: {
            total_count?: number
            sentry_integration_enabled?: number
        }
        sentryStatsLoading: boolean
    }
    selectors: {
        featureFlag: (state: any, props?: any) => FeatureFlagType
        isFeatureFlagSubmitting: (state: any, props?: any) => boolean
        showFeatureFlagErrors: (state: any, props?: any) => boolean
        featureFlagChanged: (state: any, props?: any) => boolean
        featureFlagTouches: (state: any, props?: any) => Record<string, boolean>
        featureFlagManualErrors: (state: any, props?: any) => Record<string, any>
        featureFlagMissing: (state: any, props?: any) => boolean
        isEditingFlag: (state: any, props?: any) => boolean
        insightRollingAverages: (state: any, props?: any) => {}
        affectedUsers: (state: any, props?: any) => {}
        totalUsers: (state: any, props?: any) => number | null
        featureFlagLoading: (state: any, props?: any) => boolean
        recentInsights: (state: any, props?: any) => InsightModel[]
        recentInsightsLoading: (state: any, props?: any) => boolean
        sentryStats: (
            state: any,
            props?: any
        ) => {
            total_count?: number
            sentry_integration_enabled?: number
        }
        sentryStatsLoading: (state: any, props?: any) => boolean
        currentTeamId: (state: any, props?: any) => number | null
        groupTypes: (state: any, props?: any) => Array<GroupType>
        groupsTaxonomicTypes: (state: any, props?: any) => TaxonomicFilterGroupType[]
        aggregationLabel: (
            state: any,
            props?: any
        ) => (groupTypeIndex: number | null | undefined, deferToUserWording?: boolean) => Noun
        hasAvailableFeature: (
            state: any,
            props?: any
        ) => (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        dashboards: (state: any, props?: any) => (DashboardType | DashboardBasicType)[]
        featureFlagTouched: (state: any, props?: any) => boolean
        featureFlagValidationErrors: (state: any, props?: any) => DeepPartialMap<FeatureFlagType, ValidationErrorType>
        featureFlagAllErrors: (state: any, props?: any) => Record<string, any>
        featureFlagHasErrors: (state: any, props?: any) => boolean
        featureFlagErrors: (state: any, props?: any) => DeepPartialMap<FeatureFlagType, ValidationErrorType>
        isFeatureFlagValid: (state: any, props?: any) => boolean
        sentryErrorCount: (state: any, props?: any) => number | undefined
        sentryIntegrationEnabled: (state: any, props?: any) => boolean
        props: (state: any, props?: any) => any
        multivariateEnabled: (state: any, props?: any) => boolean
        roleBasedAccessEnabled: (state: any, props?: any) => boolean
        variants: (state: any, props?: any) => MultivariateFlagVariant[]
        nonEmptyVariants: (state: any, props?: any) => MultivariateFlagVariant[]
        variantRolloutSum: (state: any, props?: any) => number
        areVariantRolloutsValid: (state: any, props?: any) => boolean
        aggregationTargetName: (state: any, props?: any) => string
        taxonomicGroupTypes: (state: any, props?: any) => TaxonomicFilterGroupType[]
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
        propertySelectErrors: (state: any, props?: any) => { properties: { value: string | undefined }[] }[]
        computeBlastRadiusPercentage: (state: any, props?: any) => (rolloutPercentage: any, index: any) => any
        approximateTotalBlastRadius: (state: any, props?: any) => number
        filteredDashboards: (state: any, props?: any) => (DashboardType | DashboardBasicType)[]
    }
    sharedListeners: {}
    values: {
        featureFlag: FeatureFlagType
        isFeatureFlagSubmitting: boolean
        showFeatureFlagErrors: boolean
        featureFlagChanged: boolean
        featureFlagTouches: Record<string, boolean>
        featureFlagManualErrors: Record<string, any>
        featureFlagMissing: boolean
        isEditingFlag: boolean
        insightRollingAverages: {}
        affectedUsers: {}
        totalUsers: number | null
        featureFlagLoading: boolean
        recentInsights: InsightModel[]
        recentInsightsLoading: boolean
        sentryStats: {
            total_count?: number
            sentry_integration_enabled?: number
        }
        sentryStatsLoading: boolean
        currentTeamId: number | null
        groupTypes: Array<GroupType>
        groupsTaxonomicTypes: TaxonomicFilterGroupType[]
        aggregationLabel: (groupTypeIndex: number | null | undefined, deferToUserWording?: boolean) => Noun
        hasAvailableFeature: (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        dashboards: (DashboardType | DashboardBasicType)[]
        featureFlagTouched: boolean
        featureFlagValidationErrors: DeepPartialMap<FeatureFlagType, ValidationErrorType>
        featureFlagAllErrors: Record<string, any>
        featureFlagHasErrors: boolean
        featureFlagErrors: DeepPartialMap<FeatureFlagType, ValidationErrorType>
        isFeatureFlagValid: boolean
        sentryErrorCount: number | undefined
        sentryIntegrationEnabled: boolean
        props: any
        multivariateEnabled: boolean
        roleBasedAccessEnabled: boolean
        variants: MultivariateFlagVariant[]
        nonEmptyVariants: MultivariateFlagVariant[]
        variantRolloutSum: number
        areVariantRolloutsValid: boolean
        aggregationTargetName: string
        taxonomicGroupTypes: TaxonomicFilterGroupType[]
        breadcrumbs: Breadcrumb[]
        propertySelectErrors: { properties: { value: string | undefined }[] }[]
        computeBlastRadiusPercentage: (rolloutPercentage: any, index: any) => any
        approximateTotalBlastRadius: number
        filteredDashboards: (DashboardType | DashboardBasicType)[]
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        sentryErrorCount: (sentryStats: {
            total_count?: number | undefined
            sentry_integration_enabled?: number | undefined
        }) => number | undefined
        sentryIntegrationEnabled: (sentryStats: {
            total_count?: number | undefined
            sentry_integration_enabled?: number | undefined
        }) => boolean
        props: (arg: any) => any
        multivariateEnabled: (featureFlag: FeatureFlagType) => boolean
        roleBasedAccessEnabled: (
            hasAvailableFeature: (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        ) => boolean
        variants: (featureFlag: FeatureFlagType) => MultivariateFlagVariant[]
        nonEmptyVariants: (variants: MultivariateFlagVariant[]) => MultivariateFlagVariant[]
        variantRolloutSum: (variants: MultivariateFlagVariant[]) => number
        areVariantRolloutsValid: (variants: MultivariateFlagVariant[], variantRolloutSum: number) => boolean
        aggregationTargetName: (
            featureFlag: FeatureFlagType,
            groupTypes: import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/types').GroupType[],
            aggregationLabel: (
                groupTypeIndex: number | null | undefined,
                deferToUserWording?: boolean | undefined
            ) => import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/models/groupsModel').Noun
        ) => string
        taxonomicGroupTypes: (
            featureFlag: FeatureFlagType,
            groupsTaxonomicTypes: TaxonomicFilterGroupType[]
        ) => TaxonomicFilterGroupType[]
        breadcrumbs: (featureFlag: FeatureFlagType) => Breadcrumb[]
        propertySelectErrors: (featureFlag: FeatureFlagType) => { properties: { value: string | undefined }[] }[]
        computeBlastRadiusPercentage: (
            affectedUsers: {},
            totalUsers: number | null
        ) => (rolloutPercentage: any, index: any) => any
        approximateTotalBlastRadius: (
            computeBlastRadiusPercentage: (rolloutPercentage: any, index: any) => any,
            featureFlag: FeatureFlagType
        ) => number
        filteredDashboards: (
            dashboards: (
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/types').DashboardType
                | DashboardBasicType
            )[],
            featureFlag: FeatureFlagType
        ) => (DashboardType | DashboardBasicType)[]
    }
}
