// Generated by kea-typegen on Thu, 20 Jul 2023 10:56:35 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { SessionRecordingDetailLogicProps } from './sessionRecordingDetailLogic'
import type { Breadcrumb } from '../../../types'

export interface sessionRecordingDetailLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'session-recordings', 'detail', 'sessionRecordingDetailLogic']
    pathString: 'scenes.session-recordings.detail.sessionRecordingDetailLogic'
    props: SessionRecordingDetailLogicProps
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        breadcrumbs: (state: any, props?: any) => Breadcrumb[]
    }
    sharedListeners: {}
    values: {
        breadcrumbs: Breadcrumb[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        breadcrumbs: (arg: any) => Breadcrumb[]
    }
}
