// Generated by kea-typegen on Sun, 06 Aug 2023 09:52:25 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ChartDisplayType, InsightLogicProps } from '../../../types'
import type { FeatureFlagsSet } from '../../../lib/logic/featureFlagLogic'
import type { BreakdownFilter, TrendsFilter } from '../../schema'

export interface insightDisplayConfigLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: string
    listeners: {}
    path: ['scenes', 'insights', 'insightDataLogic', '*']
    pathString: 'scenes.insights.insightDataLogic.*'
    props: InsightLogicProps
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        featureFlags: (state: any, props?: any) => FeatureFlagsSet
        isTrends: (state: any, props?: any) => boolean
        isFunnels: (state: any, props?: any) => boolean
        isRetention: (state: any, props?: any) => boolean
        isPaths: (state: any, props?: any) => boolean
        isStickiness: (state: any, props?: any) => boolean
        isLifecycle: (state: any, props?: any) => boolean
        supportsDisplay: (state: any, props?: any) => boolean
        showPercentStackView: (state: any, props?: any) => boolean
        breakdown: (state: any, props?: any) => BreakdownFilter | null | undefined
        display: (state: any, props?: any) => ChartDisplayType | null | undefined
        trendsFilter: (state: any, props?: any) => TrendsFilter | null | undefined
        isStepsFunnel: (state: any, props?: any) => boolean | null
        isTimeToConvertFunnel: (state: any, props?: any) => boolean | null
        isTrendsFunnel: (state: any, props?: any) => boolean | null
        isEmptyFunnel: (state: any, props?: any) => boolean | null
        showDateRange: (state: any, props?: any) => boolean
        disableDateRange: (state: any, props?: any) => boolean
        showCompare: (state: any, props?: any) => boolean
        showValueOnSeries: (state: any, props?: any) => boolean
        showUnit: (state: any, props?: any) => boolean
        showChart: (state: any, props?: any) => boolean
        showInterval: (state: any, props?: any) => boolean
        showSmoothing: (state: any, props?: any) => string | boolean
        showRetention: (state: any, props?: any) => boolean
        showPaths: (state: any, props?: any) => boolean
        showFunnelDisplayLayout: (state: any, props?: any) => boolean
        showFunnelBins: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        featureFlags: FeatureFlagsSet
        isTrends: boolean
        isFunnels: boolean
        isRetention: boolean
        isPaths: boolean
        isStickiness: boolean
        isLifecycle: boolean
        supportsDisplay: boolean
        showPercentStackView: boolean
        breakdown: BreakdownFilter | null | undefined
        display: ChartDisplayType | null | undefined
        trendsFilter: TrendsFilter | null | undefined
        isStepsFunnel: boolean | null
        isTimeToConvertFunnel: boolean | null
        isTrendsFunnel: boolean | null
        isEmptyFunnel: boolean | null
        showDateRange: boolean
        disableDateRange: boolean
        showCompare: boolean
        showValueOnSeries: boolean
        showUnit: boolean
        showChart: boolean
        showInterval: boolean
        showSmoothing: string | boolean
        showRetention: boolean
        showPaths: boolean
        showFunnelDisplayLayout: boolean
        showFunnelBins: boolean
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        showDateRange: (isRetention: boolean) => boolean
        disableDateRange: (isFunnels: boolean, isEmptyFunnel: boolean | null) => boolean
        showCompare: (isTrends: boolean, isStickiness: boolean, display: ChartDisplayType | null | undefined) => boolean
        showValueOnSeries: (
            isTrends: boolean,
            isStickiness: boolean,
            isLifecycle: boolean,
            display: ChartDisplayType | null | undefined
        ) => boolean
        showUnit: (supportsDisplay: boolean, isTrends: boolean) => boolean
        showChart: (supportsDisplay: boolean) => boolean
        showInterval: (
            isTrends: boolean,
            isStickiness: boolean,
            isLifecycle: boolean,
            isTrendsFunnel: boolean | null,
            display: ChartDisplayType | null | undefined
        ) => boolean
        showSmoothing: (
            isTrends: boolean,
            breakdown:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/queries/schema').BreakdownFilter
                | null
                | undefined,
            display: ChartDisplayType | null | undefined,
            trendsFilter:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/queries/schema').TrendsFilter
                | null
                | undefined,
            featureFlags: import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/lib/logic/featureFlagLogic').FeatureFlagsSet
        ) => string | boolean
        showRetention: (isRetention: boolean) => boolean
        showPaths: (isPaths: boolean) => boolean
        showFunnelDisplayLayout: (isStepsFunnel: boolean | null) => boolean
        showFunnelBins: (isTimeToConvertFunnel: boolean | null) => boolean
    }
}
