// Generated by kea-typegen on Thu, 20 Jul 2023 11:23:34 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { AvailableFeature, PreflightStatus, TeamPublicType, TeamType } from '../../types'
import type { GroupsAccessStatus } from './groupsAccessLogic'

export interface groupsAccessLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['lib', 'introductions', 'groupsAccessLogic']
    pathString: 'lib.introductions.groupsAccessLogic'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        currentTeam: (state: any, props?: any) => TeamType | TeamPublicType | null
        preflight: (state: any, props?: any) => PreflightStatus | null
        hasAvailableFeature: (
            state: any,
            props?: any
        ) => (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        groupsEnabled: (state: any, props?: any) => boolean
        groupsAccessStatus: (state: any, props?: any) => GroupsAccessStatus
        needsUpgradeForGroups: (state: any, props?: any) => boolean
        canStartUsingGroups: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        currentTeam: TeamType | TeamPublicType | null
        preflight: PreflightStatus | null
        hasAvailableFeature: (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        groupsEnabled: boolean
        groupsAccessStatus: GroupsAccessStatus
        needsUpgradeForGroups: boolean
        canStartUsingGroups: boolean
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        groupsEnabled: (
            hasAvailableFeature: (feature: AvailableFeature, currentUsage?: number | undefined) => boolean
        ) => boolean
        groupsAccessStatus: (
            groupsEnabled: boolean,
            currentTeam:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/types').TeamType
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/types').TeamPublicType
                | null,
            preflight:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/types').PreflightStatus
                | null
        ) => GroupsAccessStatus
        needsUpgradeForGroups: (groupsAccessStatus: GroupsAccessStatus) => boolean
        canStartUsingGroups: (groupsAccessStatus: GroupsAccessStatus) => boolean
    }
}
