// Generated by kea-typegen on Thu, 20 Jul 2023 11:24:22 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { InsightLogicProps } from '../../types'
import type { DateRange, InsightQueryNode, RetentionFilter } from '../../queries/schema'
import type { RetentionTablePayload, RetentionTrendPayload } from './types'

export interface retentionLineGraphLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: string
    listeners: {}
    path: ['scenes', 'retention', 'retentionLineGraphLogic', '*']
    pathString: 'scenes.retention.retentionLineGraphLogic.*'
    props: InsightLogicProps
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        querySource: (state: any, props?: any) => InsightQueryNode | null
        dateRange: (state: any, props?: any) => DateRange | null | undefined
        retentionFilter: (state: any, props?: any) => RetentionFilter | null | undefined
        results: (state: any, props?: any) => RetentionTablePayload[]
        trendSeries: (state: any, props?: any) => RetentionTrendPayload[]
        incompletenessOffsetFromEnd: (state: any, props?: any) => number
        aggregationGroupTypeIndex: (state: any, props?: any) => number | 'people'
    }
    sharedListeners: {}
    values: {
        querySource: InsightQueryNode | null
        dateRange: DateRange | null | undefined
        retentionFilter: RetentionFilter | null | undefined
        results: RetentionTablePayload[]
        trendSeries: RetentionTrendPayload[]
        incompletenessOffsetFromEnd: number
        aggregationGroupTypeIndex: number | 'people'
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        trendSeries: (
            results: import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/scenes/retention/types').RetentionTablePayload[],
            retentionFilter:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/queries/schema').RetentionFilter
                | null
                | undefined
        ) => RetentionTrendPayload[]
        incompletenessOffsetFromEnd: (
            dateRange:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/queries/schema').DateRange
                | null
                | undefined,
            retentionFilter:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/queries/schema').RetentionFilter
                | null
                | undefined,
            trendSeries: RetentionTrendPayload[]
        ) => number
        aggregationGroupTypeIndex: (
            querySource:
                | import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/queries/schema').InsightQueryNode
                | null
        ) => number | 'people'
    }
}
