// Generated by kea-typegen on Thu, 20 Jul 2023 10:55:11 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { TooltipItem } from '../../../../../../node_modules/.pnpm/chart.js@3.9.1/node_modules/chart.js/types/index.esm.d'
import type { SeriesDatum } from '../../InsightTooltip/insightTooltipUtils'

export interface lineGraphLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'insights', 'LineGraph', 'lineGraphLogic']
    pathString: 'scenes.insights.LineGraph.lineGraphLogic'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        createTooltipData: (
            state: any,
            props?: any
        ) => (tooltipDataPoints: TooltipItem<any>[], filterFn: (s: SeriesDatum) => boolean) => SeriesDatum[]
    }
    sharedListeners: {}
    values: {
        createTooltipData: (
            tooltipDataPoints: TooltipItem<any>[],
            filterFn: (s: SeriesDatum) => boolean
        ) => SeriesDatum[]
    }
    _isKea: true
    _isKeaWithKey: false
}
