// Generated by kea-typegen on Thu, 20 Jul 2023 11:19:52 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { TaxonomicPropertyFilterLogicProps } from '../types'
import type { AnyPropertyFilter, PropertyDefinitionType } from '../../../../types'
import type { TaxonomicFilterGroup, TaxonomicFilterValue } from '../../TaxonomicFilter/types'

export interface taxonomicPropertyFilterLogicType extends Logic {
    actionCreators: {
        selectItem: (
            taxonomicGroup: TaxonomicFilterGroup,
            propertyKey?: TaxonomicFilterValue
        ) => {
            type: 'select item (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)'
            payload: {
                taxonomicGroup: TaxonomicFilterGroup
                propertyKey: TaxonomicFilterValue | undefined
            }
        }
        openDropdown: () => {
            type: 'open dropdown (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)'
            payload: {
                value: true
            }
        }
        closeDropdown: () => {
            type: 'close dropdown (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)'
            payload: {
                value: true
            }
        }
    }
    actionKeys: {
        'select item (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)': 'selectItem'
        'open dropdown (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)': 'openDropdown'
        'close dropdown (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)': 'closeDropdown'
    }
    actionTypes: {
        selectItem: 'select item (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)'
        openDropdown: 'open dropdown (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)'
        closeDropdown: 'close dropdown (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)'
    }
    actions: {
        selectItem: (taxonomicGroup: TaxonomicFilterGroup, propertyKey?: TaxonomicFilterValue) => void
        openDropdown: () => void
        closeDropdown: () => void
    }
    asyncActions: {
        selectItem: (taxonomicGroup: TaxonomicFilterGroup, propertyKey?: TaxonomicFilterValue) => Promise<any>
        openDropdown: () => Promise<any>
        closeDropdown: () => Promise<any>
    }
    defaults: {
        dropdownOpen: boolean
    }
    events: {}
    key: string
    listeners: {
        selectItem: ((
            action: {
                type: 'select item (lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*)'
                payload: {
                    taxonomicGroup: TaxonomicFilterGroup
                    propertyKey: TaxonomicFilterValue | undefined
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['lib', 'components', 'PropertyFilters', 'components', 'taxonomicPropertyFilterLogic', '*']
    pathString: 'lib.components.PropertyFilters.components.taxonomicPropertyFilterLogic.*'
    props: TaxonomicPropertyFilterLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        dropdownOpen: boolean
    }
    reducers: {
        dropdownOpen: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        dropdownOpen: boolean
    }
    selectors: {
        dropdownOpen: (state: any, props?: any) => boolean
        filters: (state: any, props?: any) => AnyPropertyFilter[]
        taxonomicGroups: (state: any, props?: any) => TaxonomicFilterGroup[]
        describeProperty: (
            state: any,
            props?: any
        ) => (s: TaxonomicFilterValue, type: PropertyDefinitionType) => string | null
        filter: (state: any, props?: any) => AnyPropertyFilter | null
        selectedCohortName: (state: any, props?: any) => string | null | undefined
        activeTaxonomicGroup: (state: any, props?: any) => TaxonomicFilterGroup | undefined
    }
    sharedListeners: {}
    values: {
        dropdownOpen: boolean
        filters: AnyPropertyFilter[]
        taxonomicGroups: TaxonomicFilterGroup[]
        describeProperty: (s: TaxonomicFilterValue, type: PropertyDefinitionType) => string | null
        filter: AnyPropertyFilter | null
        selectedCohortName: string | null | undefined
        activeTaxonomicGroup: TaxonomicFilterGroup | undefined
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        filter: (filters: AnyPropertyFilter[], arg: any) => AnyPropertyFilter | null
        selectedCohortName: (
            filter: AnyPropertyFilter | null,
            cohorts: import('/Users/arunchaitanya/Desktop/open-source/posthog-forked/posthog/frontend/src/types').CohortType[]
        ) => string | null | undefined
        activeTaxonomicGroup: (
            filter: AnyPropertyFilter | null,
            taxonomicGroups: TaxonomicFilterGroup[]
        ) => TaxonomicFilterGroup | undefined
    }
}
