// Generated by kea-typegen on Thu, 20 Jul 2023 10:57:20 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface querySceneLogicType extends Logic {
    actionCreators: {
        setQuery: (query: string) => {
            type: 'set query (scenes.query.querySceneLogic)'
            payload: {
                query: string
            }
        }
    }
    actionKeys: {
        'set query (scenes.query.querySceneLogic)': 'setQuery'
    }
    actionTypes: {
        setQuery: 'set query (scenes.query.querySceneLogic)'
    }
    actions: {
        setQuery: (query: string) => void
    }
    asyncActions: {
        setQuery: (query: string) => Promise<any>
    }
    defaults: {
        query: string
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['scenes', 'query', 'querySceneLogic']
    pathString: 'scenes.query.querySceneLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        query: string
    }
    reducers: {
        query: (state: string, action: any, fullState: any) => string
    }
    selector: (state: any) => {
        query: string
    }
    selectors: {
        query: (state: any, props?: any) => string
    }
    sharedListeners: {}
    values: {
        query: string
    }
    _isKea: true
    _isKeaWithKey: false
}
